---
name: Publish (pypi)
on:
    push: ~

jobs:
    deploy:
        name: Publish to pypi
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Get tag
          id: vars
          run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
        - if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
          env:
            GHACTION_TAG: ${{ steps.vars.outputs.tag }}
          uses: pypa/gh-action-pypi-publish@v1.4.1
          with:
                user: __token__
                password: ${{ secrets.PYPI_API_TOKEN }}
