---
name: Publish (pypi)
on:
    push: ~

jobs:
    deploy:
        name: Publish to pypi
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GHACTION_TAG
        - if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
          uses: pypa/gh-action-pypi-publish@v1.4.1
          with:
                user: __token__
                password: ${{ secrets.PYPI_API_TOKEN }}
