---
name: Publish
on:
    push: ~

jobs:
    deploy:
        name: pypi-publish
        steps:
            - uses: pypa/gh-action-pypi-publish@v1.4.1
            - if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
            - with:
                user: __token__
                password: ${{ secrets.PYPI_API_TOKEN }}
