---
name: Quality Assurance
on:
    push: ~
    pull_request: ~

jobs:
    build:
        name: Build and test on ${{ matrix.python }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python: [ '3.5', '3.6', '3.7', '3.8' ]
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v1
              with:
                  python-version: ${{ matrix.python }}
            - run: python -m pip install --upgrade pipenv wheel
            - run: pipenv install
            - run: pipenv run "pytest"
    deploy:
        name: Publish to pypi
        runs-on: ubuntu-latest
        steps:
        - if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
          uses: pypa/gh-action-pypi-publish@@v1.4.1
          with:
                user: __token__
                password: ${{ secrets.PYPI_API_TOKEN }}
