---
name: Quality Assurance
on:
    push: ~
    pull_request: ~

jobs:
    pytest:
        name: pytest tests on ${{ matrix.python }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python: [ '3.5', '3.6', '3.7', '3.8' ]
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v1
              with:
                  python-version: ${{ matrix.python }}
            - run: pip install --user pipenv
            - run: pipenv install
            - run: pipenv run "pytest"
