---
name: Quality Assurance
on:
    push: ~
    pull_request: ~

jobs:
    build:
        name: Build and test on ${{ matrix.python }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python: [ '2.7', '3.5', '3.6', '3.7', '3.8' ]
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v1
              with:
                  python-version: ${{ matrix.python }}
            - run: python -m pip install --upgrade pipenv wheel
            - run: pipenv install
            - run: pipenv run "pytest"
